### ISSUE TITLE
chromedriver version error

### ISSUE THREAD

**Issue by ChaosTong** [TheSlientnight/douyu_helper#10]
![截屏2021-11-04 16 56 15](https://user-images.githubusercontent.com/3345527/140285540-47862f05-f0e9-474d-8dc8-d598245b61a6.png)
我更新到95版本就好了,用96都还是报错, 为什么要运行环境里的版本会变啊, 能限制吗

**Comment by TheSlientnight** [comment]
webdriver我无法进行长期维护，这个也取决于github提供的服务器内默认安装的chrome版本
