### ISSUE TITLE
请问斗鱼的COOKIES是哪个啊

### ISSUE THREAD

**Issue by DawnFaramita** [TheSlientnight/douyu_helper#2]

**Comment by DawnFaramita** [comment]
![34](https://user-images.githubusercontent.com/79857801/110749600-4def0e00-827c-11eb-8839-0732a9d29e9c.PNG)
![捕获](https://user-images.githubusercontent.com/79857801/110749604-4f203b00-827c-11eb-91cf-3ced3db268df.PNG)

**Comment by TheSlientnight** [comment]
目前处理比较粗糙，readme也正在编写
当前做法是直接通过浏览器F12找到任意接口，然后将请求头中的整个Cookie复制出来放到Secrets内，键名为COOKIES
