### ISSUE TITLE
房间页面结构改了

### ISSUE THREAD

**Issue by ChaosTong** [TheSlientnight/douyu_helper#8]
![截屏2021-10-01 21 33 06](https://user-images.githubusercontent.com/3345527/135628909-77ee50f3-c4eb-4ab4-89c2-6106d936102a.png)
应该是六点半的房间页面结构改了, 换个获取荧光棒的房间号就好了

**Comment by TheSlientnight** [comment]
感谢，我这边换个其他的直播间
